# Generated by Django 6.0.3 on 2026-03-30 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonestore', '0002_debt_transaction_delete_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='title',
        ),
        migrations.AddField(
            model_name='debt',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
    ]
