# Generated by Django 5.2.13 on 2026-04-07 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonestore', '0003_remove_debt_due_date_remove_transaction_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('phone_sale', 'Vente téléphone'), ('accessory', 'Accessoire'), ('repair', 'Réparation'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='debt',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
